### ISSUE TITLE
Feature: Kafka, NATS, and/or pluggable pubsub Support

### ISSUE THREAD

**Issue by eforbus** [adambaumeister/goflow#14]
Nice project idea! I think it would be cool to have your collector convert flows to a protobuf based payload and stream to pluggable messaging backends would really expand the potential here. That way new backends would be as simple as adding subscribers to Kafka, NATS, mqtt, etc. Thoughts?

**Comment by eforbus** [comment]
Maybe consider integration with this project to maximize the potential? 

https://github.com/Jeffail/benthos/blob/master/README.md

**Comment by adambaumeister** [comment]
I like both this idea and general concept of backends not only being traditional databases but abstract concepts.

I would think Kafka would be the logical starting point?

**Comment by adambaumeister** [comment]
Added in #15 and released as v0.15-Alpha.

**Comment by eforbus** [comment]
Awesome! Happy New Year!
